### ISSUE TITLE
2 questions

### ISSUE THREAD

**Issue by QuestionForCody** [codingneko/nerve#15]
1. Why did you delete the nerve.codingneko.com imageboard from your website?
2. Please add an email address to codingneko.com, I don't want to sign up to any service to be able to contact you

**Comment by codingneko** [comment]
I did delete it for simple reasons, I dont' feel like getting reported to the FBI, and given the fact that you guys are too stupid to keep your cheese pizza to yourself, I had to remove all the boards. I don't want that shit anywhere near me.

The code is still up for grabs, if someone feels like putting their butt on the line for freedom of speech I don't give a crap, my board was up for demonstration purposes. All you have to do to set up a board in your own server is clone the repo and throw it on an apache accessible directory (note that apache must have PHP installed) I'll be pleased to help set up a board, as long as I'm not made responsible for anything posted on it. What you post on it is not my buissness, but my servers are and I don't want to get kicked off my server provider, DNS provider, and likely get arrested for having illegal pornographic material in my servers.

As a sidenote: I did get involved with a board named libreland (running LynxChan) because I am in favour of freedom of speech and non-cucked moderation. What I was not told is that it had previous associations with CP. According to the owners, they didn't intend to allow this type of content. I hope they stand up to their words and keep this type of content off the imageboard.

You may contact me on my personal email codingneko@gmail.com if you need any further information.
